services:
  #postgres:
  #  container_name: postgres-imobiliaria
  #  image: postgres:17-alpine
  #  ports:
  #    - '5433:5432'
  #  environment:
  #    POSTGRES_USER: postgres
  #    POSTGRES_PASSWORD: docker
  #    POSTGRES_DB: imobiliaria
  #  volumes:
  #    - polls_pg:/var/lib/postgresql/data
backend-imobiliaria:
    container_name: backend-imobiliaria
    ports:
      - "98:98"
    build: ./imoboliaria-backend
    depends_on:
      - postgres
    env_file:
      - ./imoboliaria-backend/.env
    command: sh -c "npm run seed && npm start"  
volumes:
  polls_pg:
